# Allocate additional memory to the Gradle JVM. The default is often not enough to decompile Minecraft.
org.gradle.jvmargs=-Xmx2G

# Various flags to optimize Gradle performance.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true

# Enable all Gradle warnings
org.gradle.warning.mode=all

# Mod Metadata
group=io.github.Jackwastakenx2
user=Jackwastakenx2
slug=enamel
modId=enamel
modName=Th6rPGdV
modDescription=Hollow Knight/Paper Mario style Charm system, It's pin themed!
authors=Jackwastakenx2
contributors=Giggabyte
license=MIT
# Mod Version
modVersion=1.0.1
# Branch Metadata
branchName=fabric-26.1
compatibleVersions=26.1
compatibleLoaders=fabric
